/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SystemRouteImport } from './routes/system'
import { Route as PlissRouteImport } from './routes/pliss'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FlowingcartographiesRouteImport } from './routes/flowingcartographies'
import { Route as FivecropsRouteImport } from './routes/fivecrops'
import { Route as DogtownRouteImport } from './routes/dogtown'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CropSlugRouteImport } from './routes/crop.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const PlissRoute = PlissRouteImport.update({
  id: '/pliss',
  path: '/pliss',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowingcartographiesRoute = FlowingcartographiesRouteImport.update({
  id: '/flowingcartographies',
  path: '/flowingcartographies',
  getParentRoute: () => rootRouteImport,
} as any)
const FivecropsRoute = FivecropsRouteImport.update({
  id: '/fivecrops',
  path: '/fivecrops',
  getParentRoute: () => rootRouteImport,
} as any)
const DogtownRoute = DogtownRouteImport.update({
  id: '/dogtown',
  path: '/dogtown',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropSlugRoute = CropSlugRouteImport.update({
  id: '/crop/$slug',
  path: '/crop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/dogtown': typeof DogtownRoute
  '/fivecrops': typeof FivecropsRoute
  '/flowingcartographies': typeof FlowingcartographiesRoute
  '/gallery': typeof GalleryRoute
  '/pliss': typeof PlissRoute
  '/system': typeof SystemRoute
  '/tools': typeof ToolsRoute
  '/crop/$slug': typeof CropSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/dogtown': typeof DogtownRoute
  '/fivecrops': typeof FivecropsRoute
  '/flowingcartographies': typeof FlowingcartographiesRoute
  '/gallery': typeof GalleryRoute
  '/pliss': typeof PlissRoute
  '/system': typeof SystemRoute
  '/tools': typeof ToolsRoute
  '/crop/$slug': typeof CropSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/dogtown': typeof DogtownRoute
  '/fivecrops': typeof FivecropsRoute
  '/flowingcartographies': typeof FlowingcartographiesRoute
  '/gallery': typeof GalleryRoute
  '/pliss': typeof PlissRoute
  '/system': typeof SystemRoute
  '/tools': typeof ToolsRoute
  '/crop/$slug': typeof CropSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/dogtown'
    | '/fivecrops'
    | '/flowingcartographies'
    | '/gallery'
    | '/pliss'
    | '/system'
    | '/tools'
    | '/crop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credits'
    | '/dogtown'
    | '/fivecrops'
    | '/flowingcartographies'
    | '/gallery'
    | '/pliss'
    | '/system'
    | '/tools'
    | '/crop/$slug'
  id:
    | '__root__'
    | '/'
    | '/credits'
    | '/dogtown'
    | '/fivecrops'
    | '/flowingcartographies'
    | '/gallery'
    | '/pliss'
    | '/system'
    | '/tools'
    | '/crop/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditsRoute: typeof CreditsRoute
  DogtownRoute: typeof DogtownRoute
  FivecropsRoute: typeof FivecropsRoute
  FlowingcartographiesRoute: typeof FlowingcartographiesRoute
  GalleryRoute: typeof GalleryRoute
  PlissRoute: typeof PlissRoute
  SystemRoute: typeof SystemRoute
  ToolsRoute: typeof ToolsRoute
  CropSlugRoute: typeof CropSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pliss': {
      id: '/pliss'
      path: '/pliss'
      fullPath: '/pliss'
      preLoaderRoute: typeof PlissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowingcartographies': {
      id: '/flowingcartographies'
      path: '/flowingcartographies'
      fullPath: '/flowingcartographies'
      preLoaderRoute: typeof FlowingcartographiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fivecrops': {
      id: '/fivecrops'
      path: '/fivecrops'
      fullPath: '/fivecrops'
      preLoaderRoute: typeof FivecropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogtown': {
      id: '/dogtown'
      path: '/dogtown'
      fullPath: '/dogtown'
      preLoaderRoute: typeof DogtownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop/$slug': {
      id: '/crop/$slug'
      path: '/crop/$slug'
      fullPath: '/crop/$slug'
      preLoaderRoute: typeof CropSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditsRoute: CreditsRoute,
  DogtownRoute: DogtownRoute,
  FivecropsRoute: FivecropsRoute,
  FlowingcartographiesRoute: FlowingcartographiesRoute,
  GalleryRoute: GalleryRoute,
  PlissRoute: PlissRoute,
  SystemRoute: SystemRoute,
  ToolsRoute: ToolsRoute,
  CropSlugRoute: CropSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
